name: Automatic pull request review

on: 
  pull_request:
    paths:
      - jobs/**/*.json

jobs:
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Approve pull request
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: 'Test cases update.'
          
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign unassigned to author
        uses: technote-space/assign-author@v1.3.1
